export const defaultPaymentConfig = {
  baseCurrency: 'VND',
  paymentMethods: {
    payAtProperty: {
      enabled: true,
      visibleForGuests: true,
      displayName: 'Pay at property',
      description: 'Pay directly when you arrive at Lune Boutique Hotel & Apartment.',
      paymentNote: 'You can pay directly when you arrive at Lune Boutique Hotel & Apartment.',
      iconName: 'wallet',
      sortOrder: 10,
      recommended: true,
      statusAfterConfirm: 'pay_at_property',
    },
    cashAtProperty: {
      enabled: true,
      visibleForGuests: true,
      displayName: 'Cash at property',
      description: 'Pay by cash when you arrive at Lune Boutique Hotel & Apartment.',
      paymentNote: 'Cash payment is accepted at the property.',
      iconName: 'banknote',
      sortOrder: 20,
      statusAfterConfirm: 'pay_at_property',
    },
    bankTransfer: {
      enabled: false,
      visibleForGuests: false,
      displayName: 'Bank transfer',
      description: 'Transfer to the hotel account after confirmation.',
      paymentNote: 'Please only use the official bank information shown on this website.',
      iconName: 'building',
      sortOrder: 30,
      recommended: false,
      bankName: '',
      accountNumber: '',
      accountHolder: 'LUNE BOUTIQUE HOTEL',
      transferContentTemplate: 'Dang Trung Vuong chuyen tien',
      qrImageUrl: '',
      bankApiProvider: '',
      bankApiBaseUrl: '',
      webhookUrl: '',
      statusAfterConfirm: 'pending',
    },
    vietQr: {
      enabled: false,
      visibleForGuests: true,
      displayName: 'QR payment',
      description: 'Pay securely by QR code.',
      paymentNote: 'QR payment is prepared for secure online payment.',
      iconName: 'qr',
      sortOrder: 40,
      provider: 'VietQR',
      apiBaseUrl: '',
      qrImageUrl: '',
      statusAfterConfirm: 'pending',
    },
    creditCard: {
      enabled: false,
      visibleForGuests: true,
      displayName: 'Credit/Debit Card',
      description: 'Pay by international card at the property. A 5% card fee applies.',
      paymentNote: 'Card payment is settled at the property by Lune staff.',
      iconName: 'credit-card',
      sortOrder: 50,
      provider: '',
      publicKey: '',
      backendEndpoint: '/api/payments/card/create',
      webhookUrl: '',
      mode: 'test',
      statusAfterConfirm: 'pending',
    },
    stripe: {
      enabled: false,
      visibleForGuests: false,
      displayName: 'Stripe',
      description: 'Card gateway integration.',
      paymentNote: 'Card gateway payments must be confirmed by Lune staff.',
      iconName: 'credit-card',
      sortOrder: 60,
      providerName: 'Stripe',
      publicKey: '',
      backendEndpoint: '/api/payments/stripe/create',
      webhookUrl: '',
      mode: 'test',
      statusAfterConfirm: 'pending',
    },
    paypal: {
      enabled: false,
      visibleForGuests: false,
      displayName: 'PayPal',
      description: 'PayPal gateway integration.',
      paymentNote: 'PayPal payments must be confirmed by Lune staff.',
      iconName: 'wallet',
      sortOrder: 70,
      providerName: 'PayPal',
      publicKey: '',
      backendEndpoint: '/api/payments/paypal/create',
      webhookUrl: '',
      mode: 'test',
      statusAfterConfirm: 'pending',
    },
    vnpay: {
      enabled: false,
      visibleForGuests: false,
      displayName: 'VNPay',
      description: 'VNPay gateway integration.',
      paymentNote: 'VNPay payments must be confirmed by Lune staff.',
      iconName: 'wallet',
      sortOrder: 80,
      providerName: 'VNPay',
      merchantId: '',
      backendEndpoint: '/api/payments/vnpay/create',
      webhookUrl: '',
      statusAfterConfirm: 'pending',
    },
    momo: {
      enabled: false,
      visibleForGuests: false,
      displayName: 'MoMo',
      description: 'MoMo wallet integration.',
      paymentNote: 'MoMo payments must be confirmed by Lune staff.',
      iconName: 'wallet',
      sortOrder: 90,
      providerName: 'MoMo',
      merchantId: '',
      backendEndpoint: '/api/payments/momo/create',
      webhookUrl: '',
      statusAfterConfirm: 'pending',
    },
    zaloPay: {
      enabled: false,
      visibleForGuests: false,
      displayName: 'ZaloPay',
      description: 'ZaloPay wallet integration.',
      paymentNote: 'ZaloPay payments must be confirmed by Lune staff.',
      iconName: 'wallet',
      sortOrder: 100,
      providerName: 'ZaloPay',
      merchantId: '',
      backendEndpoint: '/api/payments/zalopay/create',
      webhookUrl: '',
      statusAfterConfirm: 'pending',
    },
    internationalTransfer: {
      enabled: false,
      visibleForGuests: false,
      displayName: 'International transfer',
      description: 'SWIFT or Wise transfer for international guests.',
      paymentNote: 'Please contact Lune before sending an international transfer.',
      iconName: 'landmark',
      sortOrder: 110,
      statusAfterConfirm: 'pending',
    },
  },
};

// Backward compatible named export used by older admin code.
export const paymentConfig = defaultPaymentConfig;

// Security note:
// Production payment integrations must call trusted backend endpoints.
// Never store gateway secret keys, bank API keys, webhook secrets, or card data in frontend code.
// Real API keys belong in backend .env files and verification must be handled by backend/webhooks.
