export const WORKFLOW_STATES = Object.freeze([
  'TREND_DETECTED', 'IDEA_PROPOSED', 'AWAITING_MEDIA', 'MEDIA_UPLOADED',
  'MEDIA_ANALYZING', 'MEDIA_REJECTED', 'MEDIA_READY', 'DRAFT_GENERATING',
  'DRAFT_READY', 'AWAITING_APPROVAL', 'APPROVED', 'SCHEDULED', 'PUBLISHING',
  'PUBLISH_UNKNOWN', 'PUBLISHED', 'PUBLISH_FAILED', 'PAUSED', 'ARCHIVED',
]);

const transitions = new Map(Object.entries({
  TREND_DETECTED: ['IDEA_PROPOSED', 'ARCHIVED'],
  IDEA_PROPOSED: ['AWAITING_MEDIA', 'ARCHIVED'],
  AWAITING_MEDIA: ['MEDIA_UPLOADED', 'PAUSED', 'ARCHIVED'],
  MEDIA_UPLOADED: ['MEDIA_ANALYZING', 'ARCHIVED'],
  MEDIA_ANALYZING: ['MEDIA_REJECTED', 'MEDIA_READY', 'PAUSED'],
  MEDIA_REJECTED: ['AWAITING_MEDIA', 'ARCHIVED'],
  MEDIA_READY: ['DRAFT_GENERATING', 'PAUSED', 'ARCHIVED'],
  DRAFT_GENERATING: ['DRAFT_READY', 'PUBLISH_FAILED', 'PAUSED'],
  DRAFT_READY: ['AWAITING_APPROVAL', 'APPROVED', 'ARCHIVED'],
  AWAITING_APPROVAL: ['APPROVED', 'DRAFT_READY', 'ARCHIVED'],
  APPROVED: ['SCHEDULED', 'PUBLISHING', 'ARCHIVED'],
  SCHEDULED: ['PUBLISHING', 'PAUSED', 'ARCHIVED'],
  PUBLISHING: ['PUBLISHED', 'PUBLISH_FAILED', 'PUBLISH_UNKNOWN', 'PAUSED'],
  PUBLISH_UNKNOWN: ['PUBLISHED', 'PUBLISH_FAILED', 'PAUSED'],
  PUBLISH_FAILED: ['SCHEDULED', 'PUBLISHING', 'PAUSED', 'ARCHIVED'],
  PAUSED: ['AWAITING_MEDIA', 'DRAFT_READY', 'APPROVED', 'SCHEDULED', 'ARCHIVED'],
  PUBLISHED: ['ARCHIVED'],
  ARCHIVED: [],
}));

export function canTransition(from, to) {
  return transitions.get(from)?.includes(to) ?? false;
}

export function assertTransition(from, to) {
  if (!canTransition(from, to)) {
    const error = new Error(`Invalid AI Content state transition: ${from} -> ${to}`);
    error.code = 'INVALID_STATE_TRANSITION';
    throw error;
  }
}
