// One-off: tach translations da merge (goc + extensions + overrides) thanh module rieng tung ngon ngu.
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { translations } from '../src/i18n/translations.js';

const OUT_DIR = path.resolve('src/i18n/locales');
const LANGS = Object.keys(translations);

await mkdir(OUT_DIR, { recursive: true });
for (const lang of LANGS) {
  if (!translations[lang]) throw new Error(`Missing language: ${lang}`);
  const body = `// Auto-generated by scripts/split-locales.mjs from the legacy merged translations.\nexport default ${JSON.stringify(translations[lang], null, 2)};\n`;
  await writeFile(path.join(OUT_DIR, `${lang}.js`), body);
  console.log(`${lang}.js ${(body.length / 1024).toFixed(1)} KB`);
}
